[package]
name = "final-circuit"
version = "0.1.0"
edition = "2021"

[build-dependencies]
# risc0-build = { version = "1.2.0" }
risc0-build = { git = "https://github.com/fiamma-chain/risc0", branch = "bitvm-1.2.0"}

[package.metadata.risc0]
methods = ["guest"]
